# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Amirhessam Tahmassebi
email: admin@amirhessam.com
description: >- # this means to ignore newlines until "baseurl:"
        I am currently a Data Scientist at Cerner Corporation.
        I am also an affiliated courtesy faculty in the Department 
        of Scientific Computing at Florida State University.
        This website is my Data Science Portfolio.
        
baseurl: "" # the subpath of your site, e.g. /blog
url: https://amirhessam88.github.io
#twitter_username: jekyllrb
linkedin_username: amirhessam
github_username:  amirhessam88

show_excerpts: true

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-archives

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
